### ISSUE TITLE
Report potential contaminating contigs

### ISSUE THREAD

**Issue by dparks1134** [grp-bork/gunc#11]
Hi. I'm wondering if there are plans to extend GUNC to report contigs that are likely potential contamination based on having a substantial number of incongruent genes?

**Comment by Askarbek-orakov** [comment]
Hi Donovan,

Yes, and it is high on our priority list. We are currently testing GTDB as an alternative reference database and after we finish it we will get to work on the feature of reporting potential contaminating contigs.

Thanks!

**Comment by dparks1134** [comment]
Great - looking forward to it. Thanks for the quick response.
