### ISSUE TITLE
installation failure using conda

### ISSUE THREAD

**Issue by ay-amityadav** [grp-bork/gunc#18]
I'm unable to install gunc in a separate conda environment for gunc on Ubuntu 16.04. The commands I tried and their outputs on the terminal are as below:

**Command1** `conda install -c bioconda gunc`
**Output** Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                 
UnsatisfiableError: 

**Command2** `conda install -c bioconda/label/broken gunc`
**Output** Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

ResolvePackageNotFound: 
  - prodigal

Please let me know what should I do?

Many thanks
Amit

**Comment by fullama** [comment]
what happens if you try to create a new environment just for gunc?

`conda create -n gunc -c bioconda gunc`

**Comment by ay-amityadav** [comment]
Thank you for your reply.

I had run the above two commands in a conda environment only for gunc. 

Running `conda create -n gunc -c bioconda gunc` also exits unsuccessfully.

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                 

UnsatisfiableError: 
```

**Comment by fullama** [comment]
Do you get any message after `UnsatisfiableError:`? 

Maybe you could try the suggestions here: https://github.com/grp-bork/gunc/issues/5#issuecomment-750512031

particularly the channel order: https://bioconda.github.io/user/install.html#set-up-channels

**Comment by ay-amityadav** [comment]
Setting channel order solved the issue. Thanks a lot!

**Comment by fullama** [comment]
Cool! glad we could get it sorted for you..!
