### ISSUE TITLE
**conda install** no longer finds **diamond=2.0.4**

### ISSUE THREAD

**Issue by fullama** [grp-bork/gunc#19]
**conda install** no longer finds **diamond=2.0.4**

Do you know how I could download that? (Also working in an HPCC where I am not the administrator.)

_Originally posted by @ggavelis in https://github.com/grp-bork/gunc/issues/5#issuecomment-1006085042_

**Comment by fullama** [comment]
So it looks like you don't have the bioconda channel added

Try:

conda install -c bioconda gunc

**Comment by ggavelis** [comment]
Interesting, now the error is more specific, to a missing dependency of diamond (boost Cpp).

**Command:** conda install -c bioconda gunc

**Error:**
___________________________________________

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - gunc -> diamond=2.0.4 -> boost-cpp[version='>=1.70.0,<1.70.1.0a0']

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by fullama** [comment]
Hmm probably needs the conda-forge channel too.. 
could you add the three channels as described here:

https://bioconda.github.io/user/install.html#set-up-channels

Maybe I should add a short note in the docs about this..

**Comment by ggavelis** [comment]
Thanks! It worked out for me once I specified those channels.

**Comment by fullama** [comment]
Fantastic! Glad we could sort it out.

**Comment by ggavelis** [comment]
Sorry, I jumped the gun, in that running it now produces the error:

**How I ran it:**
gunc run contigs.fasta -r /dbs/gunc/gunc_db_progenomes2.1.dmnd

**Error:**
[START] 10:45:42 2022-01-11
[ERROR] Diamond 2.0.4 not found.

**PS: how I installed it:**
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create gunc_env
conda activate gunc_env
conda install -c bioconda gunc

**Comment by ggavelis** [comment]
Fixed. Ultimately, this is what worked for me:

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda create --name gunc
source activate gunc
conda install -c bioconda diamond=2.0.4
conda install prodigal python
pip install gunc
