### ISSUE TITLE
panda KeyError: 'contig'

### ISSUE THREAD

**Issue by TianyiChang** [grp-bork/gunc#24]
Hello,

I met the panda key error (raise KeyError(key) from err KeyError: 'contig') during the diamond step, and gunc just quit running. In the "diamond_output" folder, it produced two outputs for each query fasta file, XX.diamond.progenomes_2.1.out (not empty) and XX..diamond.out (empty). There were also a few unreadable files with names like ".nfs000000000447d97c0001a098" within "diamond_output".

Could you please let me know what went wrong?

Thank you

**Comment by TianyiChang** [comment]
Below is the error message

Traceback (most recent call last):
  File "/home/tchang/.conda/envs/gunc/bin/gunc", line 10, in <module>
    sys.exit(main())
  File "/home/tchang/.conda/envs/gunc/lib/python3.10/site-packages/gunc/gunc.py", line 719, in main
    run(args)
  File "/home/tchang/.conda/envs/gunc/lib/python3.10/site-packages/gunc/gunc.py", line 617, in run
    gunc_output = run_gunc(
  File "/home/tchang/.conda/envs/gunc/lib/python3.10/site-packages/gunc/gunc.py", line 496, in run_gunc
    contig_assignments = create_contig_assignments(
  File "/home/tchang/.conda/envs/gunc/lib/python3.10/site-packages/gunc/gunc.py", line 556, in create_contig_assignments
    for contig in tax_data["contig"].unique():
  File "/home/tchang/.conda/envs/gunc/lib/python3.10/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/tchang/.conda/envs/gunc/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'contig'

Thanks a lot!

**Comment by fullama** [comment]
i have seen this error before when diamond could not map anything at all to the reference DB, the next version is being prepared for release right now that will have a clearer error message.. 

it could also be the case that diamond failed for some reason, the fact that some temporary files are left behind suggests it died unexpectedly.. is there any more output other that what you posted above? how are you running it? it might be worth running it with more time/memory?

**Comment by TianyiChang** [comment]
Hi there

Thanks for getting back! I think you are right about the source of this issue, some of the queried genomes have only a few contigs, and they produced empty diamond outputs when they were run individually.

I wonder if it is possible for gunc to continue running (with --input_dir option) even if some of the queried genomes failed the diamond step? The solution I came up with was to run all the genomes individually with a bash loop, and that would cost a lot of time to finish.

There should be enough memory and no time limit has been set. Do you think it is likely that the termination was caused by including those files with few contigs with the '--input_dir' option?

Thanks a lot!

**Comment by fullama** [comment]
it normally would continue but this specific case is not handled unfortunately.. i will make improvements in the next version so this should not happen.. unfortunately that doesnt help you right now.. sorry about that..

I could suggest maybe running in batches..? sort by size and run the bigger ones together at least they should run ok (if not then there is something else going on)

**Comment by fullama** [comment]
this should be fixed now with v1.0.6
