### ISSUE TITLE
apply GUNC to a large dataset of MAGs

### ISSUE THREAD

**Issue by PatoUru** [grp-bork/gunc#30]
Hi all,
I dont know if this is the correct place to make this question but.. I would like to know the way to run GUNC with a large dataset of MAGs (700). 
I tried with: 
for i in `cat list.txt`; do  gunc run -t 20 -i $i  -r db_gunc/gunc_db_progenomes2.1.dmnd -o gunc/; done 

The problem is that the TSV table (with the clade_separation_score) is overwritten after each round and I need to keep the previous one as well

Thank you very much!
Pat

**Comment by fullama** [comment]
you can give your `list.txt` file to gunc with the `-f` argument
