### ISSUE TITLE
diamond error

### ISSUE THREAD

**Issue by nashanghenzan** [grp-bork/gunc#33]
it seems that my computer don't support diamond 20.0..4, error info: 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  CPU does not support SSSE3. Please compile the software from source.
Aborted (core dumped)
```

**Comment by fullama** [comment]
How did you install gunc? Was it via conda?

**Comment by nashanghenzan** [comment]
> How did you install gunc? Was it via conda?

yes, it was installed via conda, but even i don't install gunc and ran diamond 20.0.4 independly, it shows the same error.

**Comment by fullama** [comment]
well you can try compiling diamond yourself https://github.com/bbuchfink/diamond/wiki/2.-Installation
conda does not seem to be installing a diamond version that will work with your cpu

**Comment by nashanghenzan** [comment]
> well you can try compiling diamond yourself https://github.com/bbuchfink/diamond/wiki/2.-Installation conda does not seem to be installing a diamond version that will work with your cpu

many thanks, i successfully compiling diamond 20.0.4！
