### ISSUE TITLE
Suppress deprecation warning from pandas

### ISSUE THREAD

**Issue by nelsonruth11** [grp-bork/gunc#37]
Hello, thank you for creating GUNC! Incredibly helpful for my current project. 

Following up on #27 , it seems this has not been resolved. I'm running GUNC v.1.0.5 installed via conda on 4/21/2023, and still get the `get_scores.py:114: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.` warning when running `gunc run --input_dir my_genomes --threads 28 --out_dir gunc_out`, where my_genomes is a directory of fasta files. 

Cheers and thanks again!
-Nelson

**Comment by fullama** [comment]
this should be fixed now with v1.0.6
