### ISSUE TITLE
Gunc merge_checkm file specification

### ISSUE THREAD

**Issue by bsiranosian** [grp-bork/gunc#4]
Thanks for the great tool! Minor issue - when running gunc merge_checkm, it appears that the checkm output file needs to contain specific columns that are only created when `checkm qa` is run with the `-o 2` (extended summary of bin quality) option. Attempting to run the merge command on the default checkm output gives the following error: 

```
Traceback (most recent call last):
  File "/labs/asbhatt/bsiranos/miniconda3/bin/gunc", line 8, in <module>
    sys.exit(main())
  File "/labs/asbhatt/bsiranos/miniconda3/lib/python3.7/site-packages/gunc/gunc.py", line 529, in main
    merge_checkm(args)
  File "/labs/asbhatt/bsiranos/miniconda3/lib/python3.7/site-packages/gunc/gunc.py", line 510, in merge_checkm
    merged = checkm_merge.merge_checkm_gunc(args.checkm_file, args.gunc_file)
  File "/labs/asbhatt/bsiranos/miniconda3/lib/python3.7/site-packages/gunc/checkm_merge.py", line 60, in merge_checkm_gunc
    'checkM.genome_size': checkmdata['Genome size (bp)'],
KeyError: 'Genome size (bp)'
```

A specificaion in the docs, or compatability with the defaul checkm output is all that's required.

**Comment by fullama** [comment]
Excellent point.. I will add it to the docs for now - it is definitely not clear how checkM should be run.. 
but i will see what i can do to improve either the error message or functionality in the new year!

Thanks for pointing that out..!

**Comment by fullama** [comment]
Should work better with the new release that is coming soon!

**Comment by franciscozorrilla** [comment]
Just wanted to point out a small typo in the docs, the `checkm qa` flag should be `–-tab_table` instead of `–tab_table`.

Also I believe that most people run [CheckM](https://github.com/Ecogenomics/CheckM/wiki/Quick-Start) via the `checkm lineage_wf` call, e.g:
```
checkm lineage_wf -t <threads> -x <extension> <input folder> <output folder>
```
I ran the `checkm qa` call on the output of the `lineage_wf`:
```
checkm qa --tab_table -t 30 -o 2 -f checkm/qa.tsv checkm/lineage.ms checkm/
```
Not sure if is redundant to run `checkm qa` if `lineage_wf` has already run (?), but this worked for merging `gunc` and `checkm` outputs.

**Comment by fullama** [comment]
Thanks for pointing that out..! restructured text always seems to find something to change unexpectedly for me.. Hopefully ive fixed that now.. 

you dont necessarily need to run `checkm qa` again - you can also just run the lineage workflow with `--tab_table -f checkm/qa.tsv` and you can use that file.. but you lose the extra columns that `-o2` adds..

Thanks again!
