### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by hexaquo** [grp-bork/gunc#5]
Hi!

I can only echo the excitement other posters have for using this tool. But I am having trouble getting the conda installation to work for the latest posted versions (1.0.0 and 1.0.1). I do not have admin privileges on the system I am installing to (it is a cluster environment - GNU/Linux   x86_64) so following the exact given instruction fails. Here is what I did instead:

1) I modified my ~.condarc file with the install destination
2) conda create -n gunc -c bioconda
3) conda install -n gunc -c bioconda gunc

This results in the install of v.0.1.2 though.

If I modify step 3 to:
conda install -n gunc -c bioconda gunc=1.0.1

Then I just get a lot of errors:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                               \  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package six conflicts for:
scipy -> mkl-service[version='>=2,<3.0a0'] -> six
numpy -> mkl-service[version='>=2,<3.0a0'] -> six
pandas -> python-dateutil[version='>=2.7.3'] -> six[version='>=1.5']
plotly -> six
plotly -> retrying[version='>=1.3.3'] -> six[version='>=1.7.0']

Package libgcc-ng conflicts for:
pandas -> libgcc-ng[version='>=7.2.0|>=7.3.0']
diamond=2.0.4 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']
diamond=2.0.4 -> libgcc-ng[version='>=7.5.0']
prodigal -> libgcc-ng[version='>=7.3.0']
numpy -> libgcc-ng[version='>=7.2.0|>=7.3.0']
numpy -> libopenblas[version='>=0.3.2,<0.3.3.0a0'] -> libgcc-ng[version='>=8.2.0']
plotly -> python -> libgcc-ng[version='>=7.2.0|>=7.3.0']
scipy -> libopenblas[version='>=0.3.2,<0.3.3.0a0'] -> libgcc-ng[version='>=8.2.0']
python[version='>=3.6'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']
requests -> python -> libgcc-ng[version='>=7.2.0|>=7.3.0']
scipy -> libgcc-ng[version='>=7.2.0|>=7.3.0']

Package libstdcxx-ng conflicts for:
python[version='>=3.6'] -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
requests -> python -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
diamond=2.0.4 -> libstdcxx-ng[version='>=7.5.0']
scipy -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
numpy -> python[version='>=3.9,<3.10.0a0'] -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
plotly -> python -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
pandas -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']

Package _libgcc_mutex conflicts for:
scipy -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
numpy -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
python[version='>=3.6'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
diamond=2.0.4 -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex=[build=main]
pandas -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
prodigal -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package numpy conflicts for:
numpy
pandas -> numpy[version='>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.13.3,<2.0a0|>=1.14.6,<2.0a0|>=1.15.4,<2.0a0|>=1.16.6,<2.0a0|>=1.9.3,<2.0a0|>=1.9']
scipy -> numpy[version='>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.6,<2.0a0|>=1.15.1,<2.0a0|>=1.9.3,<2.0a0']

Package requests conflicts for:
requests
plotly -> requests

Package pytz conflicts for:
pandas -> pytz[version='>=2017.2']
plotly -> pytz

Package setuptools conflicts for:
plotly -> setuptools
python[version='>=3.6'] -> pip -> setuptools

Package intel-openmp conflicts for:
numpy -> mkl[version='>=2019.4,<2021.0a0'] -> intel-openmp
scipy -> mkl[version='>=2019.4,<2021.0a0'] -> intel-openmp

Any advice would be appreciated!
Thanks,
Craig Herbold

**Comment by fullama** [comment]
Hmm.. conda issues like these can be notoriously difficult to get a solution to..

Some things to try:

 - Update conda `conda update conda`
 - The order of channels matters: https://bioconda.github.io/user/install.html#set-up-channels
 - This might not actually help but it might not hurt - remove unused packages/caches `conda clean -a`

after all that you could try `conda create -n gunc gunc` to create and install gunc all in one go

..it could just be that one of the dependencies is just not compatible with the version of linux you are trying to run it on.. 
Is it an older linux version/older hardware?

you could also try going down the more manual route:

`conda create -n gunc`
`conda activate gunc`
`conda install diamond=2.0.4 prodigal python`
`pip install gunc`

..this is less safe as pip will install regardless of compatibility but it could work just fine..

Hope that helps.. Let me know how you get on!

**Comment by hexaquo** [comment]
Order of channels for the win!

Thanks a lot!
Craig

**Comment by ggavelis** [comment]
**conda install** no longer finds **diamond=2.0.4**

Do you know how I could download that? (Also working in an HPCC where I am not the administrator.)
