### ISSUE TITLE
No genome2taxonomy_ref.tsv file

### ISSUE THREAD

**Issue by smb20200615** [grp-bork/gunc#8]
FileNotFoundError: [Errno 2] No such file or directory: '/conda/9ff217aa/lib/python3.9/site-packages/gunc/data/genome2taxonomy_ref.tsv'

I installed diamond prodigal and gunc using conda and get this error. I would really appreciate your thoughts.

**Comment by fullama** [comment]
Did you solve this? I would have guessed an old version (0.1.2) was installed - I am trying to get it removed to avoid these kinds of errors.

**Comment by smb20200615** [comment]
Yes I did notice the versioning! Thank you!
